### ISSUE TITLE
How to answer "yes" when it asks "ready for another pomodoro?"

### ISSUE THREAD

**Issue by genworks** [lolownia/org-pomodoro#11]
Hi,

 I just started using this and sorry if this isn't the right place for (maybe stupid) questions... is there a separate mailing list? 

Anyway my question is: after it gives me a short break, I see the 

  "Ready for another pomodoro?"

in the mini-buffer. But it's not clear to me how to answer this question -- the insertion point is not in the mini-buffer, and if I move into the mini-buffer, that question disappears...

Regards,

 Dave

**Comment by hello-code** [comment]
How to automatically start the next pomodoro ?
