### ISSUE TITLE
org-timer doing double-time for some reason

### ISSUE THREAD

**Issue by genworks** [lolownia/org-pomodoro#12]
Ok here's another one which is likely user error, but I don't know what is causing it and maybe someone has seen it. 

A couple times today I have gotten into a state where org-pomodoro starts a countdown timer from 25 minutes, but it is counting two seconds per second. It's as if two countdown timers are doing at the same time and each one is decrementing the time once per second. 

So far I haven't managed to fix it other than by exiting and restarting Emacs, which is not a solution since I usually have at least 2 or 3 swank/slime sessions going connected to remote Lisps, etc, which takes some time to re-establish.

**Comment by coyotespike** [comment]
My org-pomodoros are also doing double-time (it's a relief to see someone else had this problem!). It begins on the second pomodoro and continues from there. Org-clock records the correct amount of time, so if I double the length of my pomodoros I suppose I can work around it.

**Comment by leoc** [comment]
Hi @coyotespike is this problem persistent? Meaning, when you restart Emacs is it still there?
I were no

**Comment by coyotespike** [comment]
Hi @leoc, yes, when I restart Emacs, the first pomodoro acts normally and the subsequent pomodoros start doing double-time. Also, I just uninstalled and reinstalled org-pomodoro, and it is still doing double-time.
I'll try to think of a good minimal init, my .emacs is kind of extensive. ;-)

**Comment by leoc** [comment]
Awesome. I tried to run emacs with the latest org-pomodoro version from MELPA in a virgin emacs instance and could not reproduce the issue. But I hope we can solve this together. :+1:
