### ISSUE TITLE
Setting volume of ticking sound

### ISSUE THREAD

**Issue by mpmiszczyk** [lolownia/org-pomodoro#15]
I've found `org-pomodoro-ticking-sound-args` custom, but setting value to it does not have any effect.   And I can not find usage of this custom.

**Comment by LeoUfimtsev** [comment]
same problem here.

**Comment by leoc** [comment]
Version 1.4.1 should fix this issue. 

Thanks for reporting, I simply forgot to use this custom!
![r2](https://cloud.githubusercontent.com/assets/184696/6178896/d9501a82-b313-11e4-97f2-e39f58b9334b.gif)
