### ISSUE TITLE
can you add a hook for the count-down itself?

### ISSUE THREAD

**Issue by LeoUfimtsev** [lolownia/org-pomodoro#16]
Hello, 

I would like to set the title bar of emacs to the mode-line on every tick/tock of the pomodoro, so I could see the time remaining.

    (set-frame-parameter nil 'title (format-mode-line mode-line-format))

But I would need a hook for this. Would it be possible for you to add a hook for each tick/tock?

**Comment by leoc** [comment]
Hi, I just pushed 1.4.1 which introduces the 'org-pomodoro-tick-hook.
