### ISSUE TITLE
The short break countdown is not working

### ISSUE THREAD

**Issue by joedicastro** [lolownia/org-pomodoro#18]
Since the last update (I'm using the MELPA Stable repository, so, since the v1.5.0) the countdown is not working during the short breaks, it freezes at 5:00 and I have to stop the pomodoro timer by hand (and count manually the five minutes) to be able to use a new pomodoro timer.

**Comment by leoc** [comment]
Thanks! The timer simply didn't update the modeline anymore. Fixed that with 1.5.1.
