### ISSUE TITLE
Extending a pomodoro

### ISSUE THREAD

**Issue by srid** [lolownia/org-pomodoro#19]
Although my pomodoros end after 25 minutes, as they should, often I feel the need to continue working on a task for 5-10 minutes more.

Is there a way to extend a pomodoro, beyond the 25m mark, and end it manually? I ask only to keep the CLOCK info accurate. 

As of now, I just continue to work for those 5-10 minutes, but the CLOCK log is not accounting for it.

**Comment by LeoUfimtsev** [comment]
I'm not the developer, but I've hacked myself a function for this purpose:

    (defun my/org-pomodoro-append-time () 
    "Append time to the previous pomodoro. The time added is from when you last finished the pomodoro till now"
    (interactive)
    ; cache previous setting:
    (setq my/previous-org-clock-continuously org-clock-continuously)

    ; Start clock from previous clock-finish time.
    (setq org-clock-continuously 't)
    (org-clock-in-last)

    ;clock out right away
    (org-clock-out)

    ;restore setting.
    (setq org-clock-continuously my/previous-org-clock-continuously)
    ) 

This only works if you started at least one pomodor. It doesn't work on a fresh emacs start. But there are is a var for this also I think, something about clock consistency. I generally keep my emacs on all the time thou. 

I've also made myself a little gui for the org-pomodoro timer (linux). If interested, I added a wiki page and can explain further if something is confusing.

**Comment by srid** [comment]
Your function works, however instead of extending the pomodoro clock entry it is creating a new one:

```
	 CLOCK: [2015-02-17 Tue 21:33]--[2015-02-17 Tue 21:38] =>  0:05
	 CLOCK: [2015-02-17 Tue 21:08]--[2015-02-17 Tue 21:33] =>  0:25
```

I find this slightly problematic because it is cluttering up my agenda view with several mini chunks of tasks. It would be cleaner to represent it as one contiguous block of time, as that is in fact how the time was spent.

**Comment by leoc** [comment]
I quickly hacked a little function to adjust the last clock. I will include the function with org-pomodoro later.

```lisp
(defun org-pomodoro-extend-last-clock () 
  (save-window-excursion
    (let ((last-clock (car org-clock-history)))
      (switch-to-buffer (marker-buffer last-clock))
      (goto-char last-clock)
      (let ((item-end (save-excursion (org-end-of-subtree t))))
        (when (re-search-forward "CLOCK: \\(\\[.*?\\]\\)" item-end t)
          (kill-line)
          (org-clock-clock-out 
           (cons (copy-marker (match-end 1) t)
                 (org-time-string-to-time (match-string 1)))))))))
```

**Comment by leoc** [comment]
Added the function with 1.6.0.

**Comment by srid** [comment]
Shouldn't that function include a `(interactive)` form for invocation from M-x?
