### ISSUE TITLE
option to disable y-or-n prompt

### ISSUE THREAD

**Issue by LeoUfimtsev** [lolownia/org-pomodoro#20]
Hello, 

I sometimes cut a break short or force-stop a pomodoro if I get an interruption that I can't ignore. 

In such cases I always get that y-or-no prompt. It was nice at first, but somewhat tedious after a while in the sense that I know what I'm doing and going through the prompt kinda slows things down.

Looking at the source code, there doesn't seem to be a way to disable the y-or-no prompt via variable or force a 'y' all the time.

Would it be possible for you to add a variable/option to define this behavior?

Thank you so much for all your effort.

**Comment by LeoUfimtsev** [comment]
In the mean time I've hacked myself something together, that kinda works. (some code that renders a gui for the pomodor omitted):

    (defun my/org-pomodoro ()
      "Start a pomodoro, but without the y-or-no prompt"
      (interactive)    
      ; Kill pomodoro if it exists. Start new otherwise.
      (if (and (boundp 'org-pomodoro-countdown) (> org-pomodoro-countdown 1))
        (org-pomodoro-killed)
        (progn 
          (org-pomodoro)
        )
      ) 
    )

It would be nice to have a variable for this never the less.

**Comment by leoc** [comment]
Please use the custom `org-pomodoro-ask-upon-killing` in version 1.6.0

**Comment by LeoUfimtsev** [comment]
cool. Thank you so much.
