### ISSUE TITLE
Switch a task during a pomodoro?

### ISSUE THREAD

**Issue by LeoUfimtsev** [lolownia/org-pomodoro#21]
I sometimes finish a task and want to switch to another one while continuing with the pomodoro. 
Usually it's part of a project:

e.g:  
Project DEV-WORK
  - Sub task A  
  - Sub task B  

I will finish sub-task A and want to switch to sub-task B. I find it important to be able to tell how much time I dedicate to each sub-task.

By default, the pomodoro just continues on the old task that results in in-accurate time data on the tasks. You can only cancel a pomodoro but you can't switch to another task mid-pomodoro.

It would be nice to have the ability to switch between tasks while the pomodoro is running.

I hacked myself a solution that allows me to switch a task:

    (setq my/org-pomodoro-remaining-time 0)
    
    (defun my/org-pomodoro-switch-to-task () 
     "Switch between tasks. I.e, add the elapsed time to the old task and continue  the pomodoro on the selected task"
      (interactive)
      (setq my/org-pomodoro-remaining-time org-pomodoro-countdown) ;caches time for continue.
      (org-pomodoro-finished)  ;adds time to old task.
      (org-pomodoro-reset)     ;kills the old timer.
      (org-pomodoro) ;starts new timer.
      (setq org-pomodoro-countdown my/org-pomodoro-remaining-time) ;sets old time.
    )  

I understand that according to the book, the notion is to not switch between tasks in a pomodoro. Technically in this scenario you don't switch between projects, just between sub tasks of the same project so you don't technically break the principle. But then again the functionality can be easily miss-used. I generally favor the approach of giving people a choice of how they use the tool rather than force the tool to make a choice for people. But ultimatley the choice is yours =).

Either way, thank you for developing this great package.

**Comment by leoc** [comment]
For that you could simply use `C-c x i` (`org-clock-in`) for clocking into another task. The pomodoro will continue to count down and `org-pomodoro` would clock out accordingly. Thus you keeping your pomodoro count untouched etc.

**Comment by LeoUfimtsev** [comment]
So simple and yet so elegant. Thank you for your advice. I added it to the wiki.

**Comment by yamrock** [comment]
I was looking for this as well! Thanks!
