### ISSUE TITLE
org-clock-in-last support?

### ISSUE THREAD

**Issue by LeoUfimtsev** [lolownia/org-pomodoro#23]
I often work on a the same task for many many many pomodors. (like 50+ sometimes). 

It would be nice to have some way of starting pomodoro on the last clocked in task as does `org-clock-in-last` function.  e.g 

    F12 -> org-pomodoro-start-last-task

Some possibilities would be to either define an interactive function as above, or add an optional boolean paramater to org-pomodor so that one could call it differently depending on whether you want to start on the current selected task or continue with the previous one.

 Thank you for all your hard work!

**Comment by leoc** [comment]
If you currently invoke `org-pomodoro`, when not in a org-mode heading it will ask to choose a task from the task history.

Maybe a prefix would be nice, that always shows this history buffer.

Although, if a task gets so big (bigger than 8 pomodoros) the pomodoro manifesto (?) suggests splitting the tasks into subtasks to define actionable todos for specific goals.

**Comment by LeoUfimtsev** [comment]
Yea, I split tasks via check lists. Some of my checklists can have 50+ smaller items. Splitting it into sub-headings would make reporting messy. 

I use emacs pretty much only for org-mode. My other work is done in eclipse. As such my cursor is always beneath one heading or another. As such it would be nice to continue working on the previous task even when I'm beneath another one. Do you know what I mean?

**Comment by leoc** [comment]
Have a look at 1.7.0. `org-pomodoro` now takes a prefix argument. You can use `C-u M-x org-pomodoro` or create a custom binding invoking `org-pomodoro` with something else then `nil` as prefix arg.
