### ISSUE TITLE
Clock in last pomodoro directly, not from list?

### ISSUE THREAD

**Issue by LeoUfimtsev** [lolownia/org-pomodoro#25]
Hello, 

The org-pomodor function was changed in this issue:
https://github.com/lolownia/org-pomodoro/issues/23#event-239648311

A prefix paramater argument was added, such that:   
 - When called with nil, a pomodor starts on the selected task.
 - When called with a prefix argument, a list with recent tasks pops up and you have to press  1,2,3 etc.. to select the task.

Thank you for the additional functionality. But I was hoping for a one-press solution such that with a single keyboard button, you could start a pomodoro on the last task without selecting one from the list. I.e, using the `org-clock-in-last` function. 

Is it possible to automate either the existing code or add another optional paramater to org-pomodoro such that the most recent pomodoro would be called?

Thank you so much for your time.

**Comment by LeoUfimtsev** [comment]
maybe with 2 prefix arguments to org-pomodoro, call `org-clock-in-last` instead of `org-clock-in` ?

**Comment by leoc** [comment]
Hey, I just pushed version 2.0.0 which allows double prefix to directly clock into the last task.

`C-u C-u M-x org-pomodoro`

or

`(org-pomodoro '(16))`
