### ISSUE TITLE
can org-pomodoro have the paramater be optional?

### ISSUE THREAD

**Issue by LeoUfimtsev** [lolownia/org-pomodoro#27]
In one of the previous commits, an argument was added to the org-pomodoro function:

(defun org-pomodoro (arg)
https://github.com/lolownia/org-pomodoro/blob/master/org-pomodoro.el#L449

That kinda broke backwards compatibility that relied on it to work without para maters `(org-pomodoro)`.

While I've already changed the broken code to call it like `(org-pomodoro nil)` , I feel it might make sense to maybe make that paramater optional rather than having to call it with a nil paramater.

Like: `(defun org-pomodoro (&optional  arg) ... ` 

Thoughts?

**Comment by leoc** [comment]
Oh my. That should be an optional. Fixed in 1.7.1
