### ISSUE TITLE
adjust volume of tick?

### ISSUE THREAD

**Issue by LeoUfimtsev** [lolownia/org-pomodoro#29]
Hello, 

there is a variable `org-pomodoro-ticking-sound-args`. I tried setting it to 0.5, "0.5", 50 and "50". No effect. 

Is there an appropriate value to set to lower the volume?

I'm on linux fedora 21, with newest emacs (25.0...) and org mode.

**Comment by leoc** [comment]
Hey Leo, on linux you would have to use another player like ´mplayer´ that supports setting the volume. Then simple add the volume arguments via the custom variable you mentioned like `-v 0.3`

**Comment by leoc** [comment]
Were you able to set the volume? I adjusted the documentation strings today. You cannot simply set an integer/float value, but need to set the command line arguments for the audio player binary you are using.

**Comment by jagrg** [comment]
Using `mplayer` version `1.1-4.2.1`, this is what worked for me:

```
(setq org-pomodoro-audio-player "mplayer")
(setq org-pomodoro-finished-sound-args "-volume 0.3")
(setq org-pomodoro-long-break-sound-args "-volume 0.3")
;; (setq org-pomodoro-ticking-sound-args "-volume 0.3")
```

**Comment by leoc** [comment]
@jagrg thanks! 

I'll close this one as the docstrings should be enough to understand how to change the volume.
