### ISSUE TITLE
ticking even while on break?

### ISSUE THREAD

**Issue by LeoUfimtsev** [lolownia/org-pomodoro#30]
Hello, 

For me, the ticking continues even when on a break. 
Is there a way to turn it off when on a break?

**Comment by leoc** [comment]
With the latest version 2.0.0 you can set `org-pomodoro-ticking-sound-states` list. Normally its value is `'(:pomodoro :short-break :long-break)`. Just remove the breaks and the ticking sound only plays during a pomodoro.
