### ISSUE TITLE
Option to automatically start the next pomo?

### ISSUE THREAD

**Issue by x-ji** [lolownia/org-pomodoro#32]
Many popular pomodoro software nowadays have the option to automatically start the next pomo after your short break/long break is over. I find it OK as then I'll not have to switch back to my original `org` buffer, find the task and start again. If I wasn't actually doing work when it auto-started, I can always kill the current pomo, delete the CLOCK entry and manually start.

Could such a functionality be also added to org-pomodoro?

**Comment by hello-code** [comment]
How to automatically start the next pomodoro ?

**Comment by x-ji** [comment]
Don't think there is one yet.

**Comment by leoc** [comment]
I would suggest using a break hook to start a pomodoro on the latest task.

With the version 2.0.0 I introduced double prefix, which starts another pomodoro automatically upon a break end.

This should do the trick:

    (add-hook 'org-pomodoro-break-finished-hook
      (lambda ()
        (interactive)  
        (org-pomodoro '(16)))

**Comment by en30** [comment]
`org-pomodoro-break-finished-hook`s are run before `(org-pomodoro-reset)` and then `(org-pomodoro-active-p)` is `t`.  So `org-pomodoro` does not work as expected.

https://github.com/lolownia/org-pomodoro/blob/2.0.2/org-pomodoro.el#L543-L546
https://github.com/lolownia/org-pomodoro/blob/2.0.2/org-pomodoro.el#L498-L499
https://github.com/lolownia/org-pomodoro/blob/2.0.2/org-pomodoro.el#L506-L507

**Comment by en30** [comment]
I think using a break hook is a nice way, but it does not work in the current implementation.
Is there any reason to run `org-pomodoro-bread-finished-hook` before `(org-pomodoro-reset)`?
I am not fluent in Emacs Lisp (and also English). This does not include any offesive meaning and is just a question.

**Comment by leoc** [comment]
Hi @en30, please apologize the delay. I haven't had the time to come back earlier. 
You are completely right. The hooks should always run after the state changed. I fixed that with my latest commit.

**Comment by x-ji** [comment]
It works now. Though the only thing is that it seems the sounds are not played any more on either break end or new pomo start

**Comment by x-ji** [comment]
Never mind it seems to work well. Thank you.

**Comment by leoc** [comment]
Awsome! :+1:

**Comment by en30** [comment]
Thank you for fixing :+1:

**Comment by jmburgos** [comment]
In my case I work on many files, but I keep a single "journal" file where I keep track of my tasks and where I use org-pomodor.  So I wanted to have automatic start of the next pomodoro where the last pomodoro was clocked, and not in the file where currently I am working.  It was easy to fix...gotta love Emacs!   

```
(add-hook 'org-pomodoro-break-finished-hook
  (lambda ()
    (interactive)
    (point-to-register 1)
    (org-clock-goto)
    (org-pomodoro '(25))
    (register-to-point 1)
))
```

**Comment by MooersLab** [comment]
The above code works but there is no bell after the break and at the start of the next pomodoro.
