### ISSUE TITLE
Installation - Package not found in Emacs 25 for OS X

### ISSUE THREAD

**Issue by rogeliozarate** [lolownia/org-pomodoro#34]
Hi,
I attempted to install the package via
M-x package install RET org-pomodoro , receiving the following message:
http://melpa.milkbox.net/packages/org-pomodoro-20150331.1023.tar: Not found
Is there a workaround?
![screen shot 2015-05-30 at 11 21 59](https://cloud.githubusercontent.com/assets/64783/7898214/95a01cd4-06be-11e5-949e-32435d41a88d.png)

**Comment by leoc** [comment]
Could that be a MELPA problem? Maybe this has to do with the recent update? I pushed some changes today.

**Comment by rogeliozarate** [comment]
Could be.
What is the mechanism that takes the code from the Github repository to the MELPA tar file?

**Comment by leoc** [comment]
https://github.com/milkypostman/melpa/blob/master/package-build.el
I haven't had the time and pleasure to look into the MELPA code yet.

Maybe create issue in the melpa repository?

**Comment by rogeliozarate** [comment]
Too much code and only one life :)
I will check on MELPA's.
Thank you.

**Comment by rogeliozarate** [comment]
To fix this, update package list with:
M-x package-refresh-contents
