### ISSUE TITLE
simplify sound play: use builtin play-sound-file function instead external player. Works great in Windows.

### ISSUE THREAD

**Issue by bravosierrasierra** [lolownia/org-pomodoro#41]
```lisp
(defun org-pomodoro-play-sound (type)
  "Play an audio file specified by TYPE (:pomodoro, :short-break, :long-break)."
  (let ((sound (org-pomodoro-sound type))
        (args (org-pomodoro-sound-args type)))
    (when (and org-pomodoro-audio-player
               org-pomodoro-play-sounds
               sound)
      ;; (start-process-shell-command
      ;;  "org-pomodoro-audio-player" nil
      ;;  (mapconcat 'identity
      ;;             `(,org-pomodoro-audio-player
      ;;               ,@(delq nil (list args (shell-quote-argument sound))))
      ;;             " "))
     (play-sound-file sound)
	  )))
```

**Comment by leoc** [comment]
Hi, thanks for the hint. We used `play-sound-file` some while ago, unfortunately this function is synchronous and blocks emacs. Thus we chose to use an asynchronous process call.

Do you have problems with the audio playback on windows?

**Comment by bravosierrasierra** [comment]
on windows i see many mplayer processes and every process play its sound in infinite loop. I use many version of mplayer and problem still occur. :(

**Comment by bravosierrasierra** [comment]
in tomatinho i founded this:
(defun play-sound-file-async (file)
  "Plys with some overhead, but at least doesn't freeze Emacs."
  (let ((command (car command-line-args)))
    (start-process "play-sound-file-async" nil command "-Q" "--batch" "--eval"
                   (format "(play-sound-file \"%s\")" file))))

**Comment by leoc** [comment]
I would suggest using some player that comes with windows. Since I do not have windows I was not able to test this, but I read that `wmplayer` is an executable that you could use.

**Comment by bravosierrasierra** [comment]
Many thanks for your help! I will use tomatinho async emacs call for async play sound: it worked and my setup is still cross-platform :)

**Comment by leoc** [comment]
Alright, then I'll close! :+1:
