### ISSUE TITLE
Timer running at double-speed

### ISSUE THREAD

**Issue by dowcet** [lolownia/org-pomodoro#46]
The pomodoro counter will sometimes start running at double speed, so that it stops after 12 minutes. The timestamps are recorded correctly, but the red clock on the bottom of the window is clearly running faster then it should.  'org-pomodoro-length' is still set at 25. 

Restarting Emacs fixes the problem, until it starts happening again. I cannot reliably reproduce the problem, but it happens for me frequently. I have not gotten it to happen from a clean init.

Any idea what could possibly cause this?

**Comment by leoc** [comment]
Sorry for the delay. Do you still have this issue? Which OS, emacs version, org version, org-pomodoro version do you use? How do you install and configure `org-pomodoro`?

Cheers!

**Comment by dowcet** [comment]
It hasn't been happening lately. I've changed a lot of things (including a hack to fix #33), so I'm not sure what may have fixed it. Will close this for now.
