### ISSUE TITLE
Display the time with a progress bar

### ISSUE THREAD

**Issue by lianxiangru** [lolownia/org-pomodoro#51]
I think it will be nice looking if having this feature added. Just a suggestion.

**Comment by lianxiangru** [comment]
Oh I have achieved it by myself.

**Comment by leoc** [comment]
Hey @lianxiangru ! Cool to hear that. Maybe it would be interesting for other users of org-pomodoro how you achieved that :+1:

**Comment by lianxiangru** [comment]
@leoc Oh I just divide the time remaining by 120s and have that number of "=" in the modeline, so it will look like "[===   ]". It's not the best solution in fact :)

**Comment by mohammadanton** [comment]
Could you show me the code @ghost
