### ISSUE TITLE
Use notify-send (or arbitrary command) instead of sounds

### ISSUE THREAD

**Issue by pmiddend** [lolownia/org-pomodoro#60]
Similar to [mu4e-alert](https://github.com/iqbalansari/mu4e-alert), it would be awesome to use desktop notifications for the pomodoro steps ("starting task $x", "$minutes minutes finished", ...). Or is that possible with the current codebase?

**Comment by leoc** [comment]
We are using the `alert` package. This should be configurable to push desktop notifications.

**Comment by pmiddend** [comment]
Ah yes, I can use alert-default-style as well as `(alert-add-rule)`, thanks for the pointer.

**Comment by zacjones93** [comment]
@pmiddend Did you get the notifications working? would love to see your config! (I'm new to elisp so adding this type of functionality is rough)
