### ISSUE TITLE
Record partial pomos?

### ISSUE THREAD

**Issue by termlen0** [lolownia/org-pomodoro#63]
It would be nice to be able to save the amount of work done on a task, if we have to break/kill the pomo, say 15 minutes into it. 
Also, what if we are switching from one task to another mid clock?

**Comment by yamrock** [comment]
I think #21 is addressing this exact question. It'd be great if you can add it to the README or point to the referenced wiki.

**Comment by agzam** [comment]
But that I think doesn't address the problem, when you want to stop current pomodoro (without killing it) yet keep the record and have it as "partial", e.g.:

    CLOCK: [2017-07-16 Sun 14:41]--[2017-07-16 Sun 14:48] =>  0:07

**Comment by agzam** [comment]
So then how do I skip the break time? If you kill pomodoro it seem to not record the work done. You cannot clock-out (there's no active clock)

**Comment by jmburgos** [comment]
Actually I just noticed that there is the variable org-pomodoro-keep-killed-pomodoro-time.  If set to non nil,  partial pomodoros are saved.

**Comment by termlen0** [comment]
`org-pomodoro-keep-killed-pomodoro-time` makes a lot of sense! Thanks, closing issue
